import { PlanData } from '@/types/plan';

/**
 * 旅行プランのデータを Markdown 形式に変換するよ！
 * Notion や Slack に貼り付けた時に綺麗に見えるように調整しているんだ。✨
 */
export const convertPlanToMarkdown = (plan: PlanData): string => {
  // タイトル
  let md = `# ${plan.title}\n\n`;

  // 日ごとのスケジュール
  plan.days.forEach((day) => {
    md += `## ${day.day}日目\n\n`;
    day.schedule.forEach((item) => {
      // 時間と場所を太字に
      md += `### ${item.time} ${item.place}\n`;
      // 説明文
      md += `${item.description}\n\n`;
    });
  });

  // 宿泊先情報
  md += `## おすすめの宿泊先 🏨\n\n`;
  plan.hotels.forEach((hotel) => {
    md += `### ${hotel.name}\n`;
    md += `- **エリア**: ${hotel.area}\n`;
    md += `- **価格目安**: ${hotel.price}\n`;
    md += `- **特徴**: ${hotel.features.join(' / ')}\n\n`;
  });

  // フッターっぽく
  md += `---\n*Generated by Fuwari ☁️*`;

  return md;
};
